export const ADD_USER = 'ADD_USER';
export const ADD_FAVORITE_EVENT = 'ADD_FAVORITE_EVENT';
export const REMOVE_FAVORITE_EVENT = 'REMOVE_FAVORITE_EVENT';
export const TOGGLE_FAVORITE_EVENT = 'TOGGLE_FAVORITE_EVENT';
export const LOGOUT = 'LOGOUT';
